apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-edge
spec:
  selector:
    matchLabels:
      app: patient-edge
  replicas: 1
  template:
    metadata:
      labels:
        app: patient-edge
    spec:
      # hostNetwork: true
      nodeName: zzy-raspberrypi
      containers:
      - name: patient-edge
        image: patient-edge:v1.0.4
        imagePullPolicy: IfNotPresent # 如果image为本地构建则需要该参数
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-mysql
spec:
  selector:  
    matchLabels:
      app: edge-mysql
  replicas: 1 
  template: 
    metadata:
      labels:
        app: edge-mysql
    spec:
      nodeName: zzy-raspberrypi
      containers:
      - name: mysql
        image: mysql
        ports:
          - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: 2002116yy
        command: ['sh', '-c', 'mysql -uroot -p"$MYSQL_ROOT_PASSWORD" < /scripts/script.sql']
        volumeMounts:
        - name: scripts
          mountPath: /scripts
      volumes:
      - name: scripts
        configMap:
          name: edge-mysql-scripts
---
apiVersion: v1
kind: Service
metadata:
  name: edge-mysql
spec:
  ports:
  - port: 3306
  selector:
    app: edge-mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-mqtt
spec:
  selector:  
    matchLabels:
      app: edge-mqtt
  replicas: 1 
  template: 
    metadata:
      labels:
        app: edge-mqtt
    spec:
      # hostNetwork: true
      # dnsPolicy: ClusterFirstWithHostNet
      nodeName: zzy-raspberrypi
      containers:
      - name: mqtt
        image: eclipse-mosquitto:1.6.15
        ports:
        - containerPort: 1883
          hostPort: 1883
---
apiVersion: v1
kind: Service
metadata:
  name: edge-mqtt
spec:
  ports:
  - port: 1883
  selector:
    app: edge-mqtt
